/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatsNewRouteImport } from './routes/whats-new'
import { Route as RecommendationLetterRouteImport } from './routes/recommendation-letter'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MeetingMomRouteImport } from './routes/meeting-mom'
import { Route as MeetingAgendaRouteImport } from './routes/meeting-agenda'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DczmcRouteImport } from './routes/dczmc'
import { Route as CzmpRouteImport } from './routes/czmp'
import { Route as CourtMattersRouteImport } from './routes/court-matters'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const WhatsNewRoute = WhatsNewRouteImport.update({
  id: '/whats-new',
  path: '/whats-new',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationLetterRoute = RecommendationLetterRouteImport.update({
  id: '/recommendation-letter',
  path: '/recommendation-letter',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingMomRoute = MeetingMomRouteImport.update({
  id: '/meeting-mom',
  path: '/meeting-mom',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingAgendaRoute = MeetingAgendaRouteImport.update({
  id: '/meeting-agenda',
  path: '/meeting-agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DczmcRoute = DczmcRouteImport.update({
  id: '/dczmc',
  path: '/dczmc',
  getParentRoute: () => rootRouteImport,
} as any)
const CzmpRoute = CzmpRouteImport.update({
  id: '/czmp',
  path: '/czmp',
  getParentRoute: () => rootRouteImport,
} as any)
const CourtMattersRoute = CourtMattersRouteImport.update({
  id: '/court-matters',
  path: '/court-matters',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact-us': typeof ContactUsRoute
  '/court-matters': typeof CourtMattersRoute
  '/czmp': typeof CzmpRoute
  '/dczmc': typeof DczmcRoute
  '/faq': typeof FaqRoute
  '/meeting-agenda': typeof MeetingAgendaRoute
  '/meeting-mom': typeof MeetingMomRoute
  '/notifications': typeof NotificationsRoute
  '/projects': typeof ProjectsRoute
  '/recommendation-letter': typeof RecommendationLetterRoute
  '/whats-new': typeof WhatsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact-us': typeof ContactUsRoute
  '/court-matters': typeof CourtMattersRoute
  '/czmp': typeof CzmpRoute
  '/dczmc': typeof DczmcRoute
  '/faq': typeof FaqRoute
  '/meeting-agenda': typeof MeetingAgendaRoute
  '/meeting-mom': typeof MeetingMomRoute
  '/notifications': typeof NotificationsRoute
  '/projects': typeof ProjectsRoute
  '/recommendation-letter': typeof RecommendationLetterRoute
  '/whats-new': typeof WhatsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact-us': typeof ContactUsRoute
  '/court-matters': typeof CourtMattersRoute
  '/czmp': typeof CzmpRoute
  '/dczmc': typeof DczmcRoute
  '/faq': typeof FaqRoute
  '/meeting-agenda': typeof MeetingAgendaRoute
  '/meeting-mom': typeof MeetingMomRoute
  '/notifications': typeof NotificationsRoute
  '/projects': typeof ProjectsRoute
  '/recommendation-letter': typeof RecommendationLetterRoute
  '/whats-new': typeof WhatsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact-us'
    | '/court-matters'
    | '/czmp'
    | '/dczmc'
    | '/faq'
    | '/meeting-agenda'
    | '/meeting-mom'
    | '/notifications'
    | '/projects'
    | '/recommendation-letter'
    | '/whats-new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact-us'
    | '/court-matters'
    | '/czmp'
    | '/dczmc'
    | '/faq'
    | '/meeting-agenda'
    | '/meeting-mom'
    | '/notifications'
    | '/projects'
    | '/recommendation-letter'
    | '/whats-new'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact-us'
    | '/court-matters'
    | '/czmp'
    | '/dczmc'
    | '/faq'
    | '/meeting-agenda'
    | '/meeting-mom'
    | '/notifications'
    | '/projects'
    | '/recommendation-letter'
    | '/whats-new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactUsRoute: typeof ContactUsRoute
  CourtMattersRoute: typeof CourtMattersRoute
  CzmpRoute: typeof CzmpRoute
  DczmcRoute: typeof DczmcRoute
  FaqRoute: typeof FaqRoute
  MeetingAgendaRoute: typeof MeetingAgendaRoute
  MeetingMomRoute: typeof MeetingMomRoute
  NotificationsRoute: typeof NotificationsRoute
  ProjectsRoute: typeof ProjectsRoute
  RecommendationLetterRoute: typeof RecommendationLetterRoute
  WhatsNewRoute: typeof WhatsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whats-new': {
      id: '/whats-new'
      path: '/whats-new'
      fullPath: '/whats-new'
      preLoaderRoute: typeof WhatsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendation-letter': {
      id: '/recommendation-letter'
      path: '/recommendation-letter'
      fullPath: '/recommendation-letter'
      preLoaderRoute: typeof RecommendationLetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meeting-mom': {
      id: '/meeting-mom'
      path: '/meeting-mom'
      fullPath: '/meeting-mom'
      preLoaderRoute: typeof MeetingMomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meeting-agenda': {
      id: '/meeting-agenda'
      path: '/meeting-agenda'
      fullPath: '/meeting-agenda'
      preLoaderRoute: typeof MeetingAgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dczmc': {
      id: '/dczmc'
      path: '/dczmc'
      fullPath: '/dczmc'
      preLoaderRoute: typeof DczmcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/czmp': {
      id: '/czmp'
      path: '/czmp'
      fullPath: '/czmp'
      preLoaderRoute: typeof CzmpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/court-matters': {
      id: '/court-matters'
      path: '/court-matters'
      fullPath: '/court-matters'
      preLoaderRoute: typeof CourtMattersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactUsRoute: ContactUsRoute,
  CourtMattersRoute: CourtMattersRoute,
  CzmpRoute: CzmpRoute,
  DczmcRoute: DczmcRoute,
  FaqRoute: FaqRoute,
  MeetingAgendaRoute: MeetingAgendaRoute,
  MeetingMomRoute: MeetingMomRoute,
  NotificationsRoute: NotificationsRoute,
  ProjectsRoute: ProjectsRoute,
  RecommendationLetterRoute: RecommendationLetterRoute,
  WhatsNewRoute: WhatsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
